use_frameworks!

target 'CardTransition_Example' do
  pod 'CardTransition', :path => '../'

  target 'CardTransition_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
